name: Publish anibali/pytorch:1.4.0-cuda10.1-ubuntu16.04

on:
  push:
    branches:
    - master
    paths:
    - dockerfiles/1.4.0-cuda10.1-ubuntu16.04/*
    - .github/workflows/publish_1.4.0-cuda10.1-ubuntu16.04.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: anibali/pytorch
        tags: 1.4.0-cuda10.1-ubuntu16.04,1.4.0-cuda10.1
        path: dockerfiles/1.4.0-cuda10.1-ubuntu16.04
