name: Publish anibali/pytorch:1.4.0-nocuda-ubuntu16.04

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: anibali/pytorch
        tags: 1.4.0-nocuda-ubuntu16.04,1.4.0-nocuda
        path: dockerfiles/1.4.0-nocuda-ubuntu16.04
