name: Publish anibali/pytorch:1.13.0-cuda11.8-ubuntu22.04

on:
  push:
    branches:
    - master
    paths:
    - dockerfiles/1.13.0-cuda11.8-ubuntu22.04/*
    - .github/workflows/publish_1.13.0-cuda11.8-ubuntu22.04.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: anibali/pytorch
        tags: 1.13.0-cuda11.8-ubuntu22.04,1.13.0-cuda11.8,latest
        path: dockerfiles/1.13.0-cuda11.8-ubuntu22.04
