name: Publish anibali/pytorch:1.5.0-cuda10.2-ubuntu18.04

on:
  push:
    branches:
    - master
    paths:
    - dockerfiles/1.5.0-cuda10.2-ubuntu18.04/*
    - .github/workflows/publish_1.5.0-cuda10.2-ubuntu18.04.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: anibali/pytorch
        tags: 1.5.0-cuda10.2-ubuntu18.04,1.5.0-cuda10.2,latest
        path: dockerfiles/1.5.0-cuda10.2-ubuntu18.04
